Feature/exercicio 2
luispaulobrito/Orion-Bootcamp pull request #2
Opened 2023-10-10 21:29 UTC by luispaulobrito

2023-10-10 22:23 UTC, Ricardonovais1 commented
![](https://github.trello.services/images/mini-trello-icon.png) [[Ricardo Novais] Exercício-02](https://trello.com/c/muGjhphd/85-ricardo-novais-exerc%C3%ADcio-02)

2023-10-11 21:45 UTC, aLiviaMs requested changes

2023-10-11 21:45 UTC, aLiviaMs commented on exercicios/src/app/segundo-exercicio-funcional/segundo-exercicio-funcional.component.ts
> +  isStringValid(value: string){
É importante tipar o retorno de todas as funções do código.
É importante tipar todas as variaveis do código também.

Algumas estão em falta

2023-10-11 21:45 UTC, aLiviaMs commented on exercicios/src/app/segundo-exercicio-imperativo/segundo-exercicio-imperativo.component.ts
> +    return this.lista.find(item => item.id === id);
a utilização de .find entra no paradigma funcional.

 ``` 
for (let i = 0; i < lista.length; i++) {
    if (lista[i].id === id) {
      return lista[i];
    }
  }
  return;
```

Esse seria um exemplo de um paradigma imperativo

2023-10-13 15:04 UTC, aLiviaMs approved these changes

2023-10-13 15:04 UTC, merged